### ISSUE TITLE
Spawn Chunk Handling

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#112]
During the Beta 1.X Debugging session, several dozen unexplained issues have been discovered which only occur in the spawn chunk/protection area. These issues are bizarre, annoying, obscure, and plentiful.

As such, the spawn chunk warning is now *very* important to user experience; detection should be flawless and the message should be prominent.

## Colouring.
Currently, the spawn chunk error uses the "positive" green prefix.
This error message should instead use the "negative" red prefix.
![image](https://user-images.githubusercontent.com/49039536/154820801-defc9c76-fcb5-4b1c-8303-de7e1bf67c3c.png)

### Ideal
Spawn protection is centred upon the world's vanilla spawn point.
This can be changed with `setworldspawn`

It extends rectangularly outwards *n* blocks from that point.
![image](https://user-images.githubusercontent.com/49039536/154821064-c3fcca33-be02-420d-b96f-228ea88643bb.png)

*n* is specified by the user in `server.properties` as `spawn-protection`.
![image](https://user-images.githubusercontent.com/49039536/154821080-3772c1d6-fbc9-4987-b23c-1849a33831aa.png)

### Current.
Our current detection is centred upon that point, however, appears to use a radius.
It is also unclear as to whether our current detection accounts for the value specified by the user.

As such, it is currently possible to create a portal that is within spawn protection, yet not within our notification area.
![image](https://user-images.githubusercontent.com/49039536/154821030-d019d1b8-ecd2-4f65-87dc-eb2e3103fbc0.png)

**Comment by EpicKnarvik97** [comment]
Additional bug: The current check only accounts for whether the sign is within the spawn area, which means that a Stargate can be mostly inside the spawn area as long as the sign is outside, and display no warnings.

Spawn radius is given by: `Bukkit.getServer().getSpawnRadius()` which seemingly gets the value set in the config file.

It seems the bug is in the comparison between the sign location and the spawn location. The spawn point is subtracted from the sign location and the difference is compared (which only works in a few cases).

**Comment by EpicKnarvik97** [comment]
82ee4bb and 4feb2dd should fix this with some help from 10e9f6f. Tests seem to imply that all relevant bugs have been fixed. If not, feel free to re-open this issue.
