### ISSUE TITLE
[TMS TMP005] U gates fail to connect.

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#252]
```
test1
test2
server1
U
```
```
test2
test1
server2
U
```

does not appear to work within the test environment.
![image](https://user-images.githubusercontent.com/49039536/209165193-25fe9c5b-95e3-4247-a7f3-45fb5bf87525.png)
![image](https://user-images.githubusercontent.com/49039536/209165278-a7848620-cc75-468a-94ff-c472e7f78658.png)

**Comment by Thorinwasher** [comment]
I don't understand this issue. You made 2 portals on 2 different custom networks and tried to connect the two. Or is this legacy bungee gates? The behavior of that sign does not match with legacy bungee gates though.

**Comment by Pheotis** [comment]
Whoops; I forgot to show the U flag on the syntax example in the initial issue post - -fixed.
Yes, this is legacy bungee gates.

The syntax was based on the U flag's description in the current documentation
![image](https://user-images.githubusercontent.com/49039536/209573121-ef3c2a07-2c76-4b31-a516-aa34376b632c.png)

**Comment by Thorinwasher** [comment]
I can't replicate this with the most recent release

**Comment by Thorinwasher** [comment]
Are you sure this is not a permission issue, where you lack permission to create a bungee portal or something like that? Although there should be a creation error message or something.

But in essence: this portal is not a bungee portal, but a fixed portal. This is because it has certain formatting on a sign that makes it so. A legacy bungee portal has the following formatting;
```
name
destination
destinationServer
LEGACY BUNGEE
```
It should also be completely unable to show the [Disconnected] message, as it's impossible to know whether it is connected or not, as this is in another server. For that  it requires the portals to share a database, or alternativly requiring velocity or similar as a proxy

**Comment by Pheotis** [comment]
I am confident that the portal in question had the `U` flag, and that sufficient permissions were available.
Having said that, I am also currently unable to reproduce this, so I am going to close this issue as CNR for now.

**Comment by Thorinwasher** [comment]
I'm very confident that the portal did not have the `U` flag, because of this:
```java
        String[] lines = new String[4];
        lines[0] = super.colorDrawer.formatPortalName(this, HighlightingStyle.MINUS_SIGN);
        lines[1] = super.colorDrawer.formatPortalName(getDestination(), HighlightingStyle.LESSER_GREATER_THAN);
        lines[2] = super.colorDrawer.formatStringWithHiglighting(serverDestination, HighlightingStyle.SQUARE_BRACKETS);
        lines[3] = super.colorDrawer.formatLine(bungeeString);
        getGate().drawControlMechanisms(lines, !hasFlag(PortalFlag.ALWAYS_ON));
```
This is the code that draws the sign for legacy bungee. Note that the last line of the sign (line 3) is the bungee translatable message.

So the portal could not have been bungee
